### PR TITLE
Bugfix: For issue #135 

### PR DESCRIPTION
**Pull request by samvarankashyap**
Summary: 
- Updated the config_file paths
- Removed unwanted override of config_file in common role
- Updated and removed debug statements in linchpin_api

### CODE REVIEW

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
@herlo : something might have changed due pip package, because previously linchpin_config file generated used to go into the /usr/lib/python2.7/site-packages/linchpin-0.8.3-py2.7.egg/  when we perform python setup.py install . However , when we do a pip install linchpin the linchpin_config.yml is generated in /usr/linchpin_config.yml.

**Comment by herlo** [comment]
Keep in mind that /usr is outside of a virtualenv, at a minimum and that linchpin_config.yml should be probably found in [PYTHON_PATH]/linchpin-<version>.egg/. If it is not there, it should be in /etc/linchpin/ maybe? The home_dir and cwd paths are ones a dev would have to generate on their own.

**Comment by robled** [comment]
Has this fix made its way to PyPi yet?  I'm currently running linchpin 8.8.6 from PyPi and can still reproduce this error:

```
(cinch) [vagrant@localhost test]$ linchpin rise
debug:: searching linchpin_config file from path ::
/home/vagrant/test/linchpin_config.yml
debug:: searching linchpin_config file from path ::
/home/vagrant/test/linch-pin/linchpin_config.yml
debug:: searching linchpin_config file from path ::
~/.linchpin_config.yml
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/lib/python2.7/site-packages/linchpin_config.yml
debug:: searching linchpin_config file from path ::
/etc/linchpin_config.yml
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/bin
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/lib/python27.zip
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/lib64/python2.7
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/lib64/python2.7/plat-linux2
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/lib64/python2.7/lib-tk
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/lib64/python2.7/lib-old
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/lib64/python2.7/lib-dynload
debug:: searching linchpin_config file from path ::
/usr/lib64/python2.7
debug:: searching linchpin_config file from path ::
/usr/lib/python2.7
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/lib/python2.7/site-packages
debug:: searching linchpin_config file from path ::
/home/vagrant/test/linchpin_config.yml
debug:: searching linchpin_config file from path ::
/home/vagrant/test/linch-pin/linchpin_config.yml
debug:: searching linchpin_config file from path ::
~/.linchpin_config.yml
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/lib/python2.7/site-packages/linchpin_config.yml
debug:: searching linchpin_config file from path ::
/etc/linchpin_config.yml
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/bin
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/lib/python27.zip
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/lib64/python2.7
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/lib64/python2.7/plat-linux2
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/lib64/python2.7/lib-tk
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/lib64/python2.7/lib-old
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/lib64/python2.7/lib-dynload
debug:: searching linchpin_config file from path ::
/usr/lib64/python2.7
debug:: searching linchpin_config file from path ::
/usr/lib/python2.7
debug:: searching linchpin_config file from path ::
/home/vagrant/cinch/lib/python2.7/site-packages
debug::print file path
None
Traceback (most recent call last):
  File "/home/vagrant/cinch/bin/linchpin", line 11, in <module>
    sys.exit(cli())
  File "/home/vagrant/cinch/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/cinch/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/cinch/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/cinch/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/cinch/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/cinch/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/vagrant/cinch/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/cinch/lib/python2.7/site-packages/linchpin.py", line 191, in rise
    output = lpcli.lp_rise(pf, target)
  File "/home/vagrant/cinch/lib/python2.7/site-packages/cli/cli.py", line 86, in lp_rise
    pf)
  File "/home/vagrant/cinch/lib/python2.7/site-packages/cli/cli.py", line 22, in find_topology
    config = self.get_config()
  File "/home/vagrant/cinch/lib/python2.7/site-packages/linchpin_api/v1/api.py", line 55, in get_config
    config = parse_yaml(config_path)
  File "/home/vagrant/cinch/lib/python2.7/site-packages/linchpin_api/v1/utils.py", line 31, in parse_yaml
    with open(pf, 'r') as stream:
TypeError: coercing to Unicode: need string or buffer, NoneType found
(cinch) [vagrant@localhost test]$ pip freeze | grep linch
linchpin==0.8.6
(cinch) [vagrant@localhost test]$ find ../cinch -name linchpin_config.yml
../cinch/linchpin_config.yml
../cinch/lib/python2.7/site-packages/tests/playbooks/linchpin_config.yml
```

**Comment by greg-hellings** [comment]
Like David, I'm still seeing this same behavior from both the released version and from master HEAD.

**Comment by herlo** [comment]
I am currently working on fixing this problem.

**Pull request merged**
