### PR TITLE
Bugfix for Inventory to Host ip mapping 

### LINKED ISSUE #153: BUG: Inventory file doesn't match created VMs
For more information internal to RedHat, please contact me.
Using the following inventory file:
http://pastebin.test.redhat.com/456191
The following layout file:
http://pastebin.test.redhat.com/456192
I get the following inventory file:
http://pastebin.test.redhat.com/456190

However the IP addresses don't match the VMs in openstack. Here's a screenshot of the openstack list:
screenshot from 2017-02-16 09-48-43

### PR DESCRIPTION
**Pull request by samvarankashyap**
Summary:
- added ordered_yaml filter to parse inventory_layout file
- updated InventoryFilters , inventory_gen role to reflect the changes
- updated requirements.txt

Fixes #153

### CODE REVIEW

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
@herlo All tests have passed

**Comment by herlo** [comment]
requirements.txt still needs to have camel listed, or install fails:
```
$ pip install file:///home/herlo/Projects/linch-pin
Processing /home/herlo/Projects/linch-pin
..snip..

$ $ linchpin rise
debug:: searching linchpin_config file from path :: 
/home/herlo/Projects/lptest/linchpin_config.yml
debug:: searching linchpin_config file from path :: 
/home/herlo/Projects/lptest/linch-pin/linchpin_config.yml
debug:: searching linchpin_config file from path :: 
~/.linchpin_config.yml
debug:: searching linchpin_config file from path :: 
/home/herlo/Projects/virtualenvs/venv/lib/python2.7/site-packages/linchpin_config.yml
debug:: File found returning ::
/home/herlo/Projects/virtualenvs/venv/lib/python2.7/site-packages/linchpin_config.yml
debug:: searching linchpin_config file from path :: 
/home/herlo/Projects/lptest/linchpin_config.yml
debug:: searching linchpin_config file from path :: 
/home/herlo/Projects/lptest/linch-pin/linchpin_config.yml
debug:: searching linchpin_config file from path :: 
~/.linchpin_config.yml
debug:: searching linchpin_config file from path :: 
/home/herlo/Projects/virtualenvs/venv/lib/python2.7/site-packages/linchpin_config.yml
debug:: File found returning ::
/home/herlo/Projects/virtualenvs/venv/lib/python2.7/site-packages/linchpin_config.yml
debug::print file path
/home/herlo/Projects/virtualenvs/venv/lib/python2.7/site-packages/linchpin_config.yml
Finding topology in local folder ./topology
debug:: searching linchpin_config file from path :: 
/home/herlo/Projects/lptest/linchpin_config.yml
debug:: searching linchpin_config file from path :: 
/home/herlo/Projects/lptest/linch-pin/linchpin_config.yml
debug:: searching linchpin_config file from path :: 
~/.linchpin_config.yml
debug:: searching linchpin_config file from path :: 
/home/herlo/Projects/virtualenvs/venv/lib/python2.7/site-packages/linchpin_config.yml
debug:: File found returning ::
/home/herlo/Projects/virtualenvs/venv/lib/python2.7/site-packages/linchpin_config.yml
debug::print file path
/home/herlo/Projects/virtualenvs/venv/lib/python2.7/site-packages/linchpin_config.yml
Finding layout in local folder ./layouts
{'linchpin_config': '/home/herlo/Projects/virtualenvs/venv/lib/python2.7/site-packages/linchpin_config.yml', 'inventory_layout_file': '/home/herlo/Projects/lptest/layouts/openshift-3node-cluster.yml', 'state': 'present', 'outputfolder_path': '/home/herlo/Projects/lptest/outputs', 'inventory_outputs_path': '/home/herlo/Projects/lptest/inventories', 'topology': '/home/herlo/Projects/lptest/topologies/simple-libvirt-cluster.yml'}
debug:: module path ::/home/herlo/Projects/virtualenvs/venv/lib/python2.7/site-packages/library

PLAY [including the configuration files] ***************************************

TASK [Include linchpin_config] *************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named camel
fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
	to retry, use: --limit @/home/herlo/Projects/virtualenvs/venv/lib/python2.7/site-packages/provision/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

After adding camel to the requirements.txt, this error does not occur.

**Comment by herlo** [comment]
also, we should probably perform a pip install in this way in our testing to show that it works, along with a linchpin rise in a test directory using openstack or something. I'm still not getting things to work properly in certain edge cases.

**Comment by herlo** [comment]
I'm confident this fix is correct. After fixing the camel issue, and retesting everything, it should be good to merge.

**Comment by samvarankashyap** [comment]
@herlo : Re-based with updated master branch and fixed requirements.txt

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
@herlo After adding camel to requirements.txt the error still persists.
when i do python setup.py install in virtualenv the following happens
```
Reading https://github.com/eevee/camel/tree/v0.1/tarball/
Reading https://pypi.python.org/simple/camel/
Downloading https://pypi.python.org/packages/2b/f6/3e00c732983c7c233823b72086911c1d05cc1c9e7a6556967a83b6e65159/camel-0.1.tar.gz#md5=120a86185280d209c1c738ce3e7bf016
Best match: camel 0.1
Processing camel-0.1.tar.gz
Writing /tmp/easy_install-cbrcQb/camel-0.1/setup.cfg
Running camel-0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-cbrcQb/camel-0.1/egg-dist-tmp-WNhhAo
error: [Errno 2] No such file or directory: 'README.txt'

```

**Comment by arilivigni** [comment]
FYI and you guys probably know this and have a better solution.  I have been reading up on the installation using pip or setup.py.  I tried running setup.py and it fails.

The only consistent way of installing that has worked for me is to run: 
1 - virtualenv --no-site-packages
2 - run ./install.sh that runs pip install line by line of the requirements.txt
3 - Copy site packages for selinux into virtual env

It is the only consistent way that has worked for me

**Comment by herlo** [comment]
@arilivigni, Yes we do know about the errors. However, it actually does work with pip by doing the following:

1 - mkvirtualenv --clear -a venv venv
2 - pip install file:///path/to/linch-pin
3 - cd venv/lib/python2.7/site-packages
4 - ln -s /usr/lib/python2.7/site-packages/selinux/
5 - ln -s /usr/lib/python2.7/site-packages/_selinux.so
6 - cp /path/to/linch-pin/linchpin_config.yml

This, is of course, after @samvarankashyap fixes the camel package issue, which should just need to be in requirements.txt. I don't think the install.sh is necessary if you perform the tasks in this way. If you use 'python setup.py install', it will require you use the install.sh.

**Comment by herlo** [comment]
Oh, I guess I missed that he has added camel to the requirements.txt. I'll be testing this out later today. :+1:

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Pull request merged**
