### PR TITLE
added python-krbV optional dependency for Beaker

### LINKED ISSUE #177: Missing dependency for python-krbV
This package is needed for Beaker provisioning.

```
TASK [beaker : provision beaker systems] ***************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named krbV
```

### PR DESCRIPTION
**Pull request by robled**
Fixes #177

### CODE REVIEW

**Comment by samvarankashyap** [comment]
@robled : Was wondering why python-krbv was not added as a dependency in beaker's PyPi package if beaker needs it.

**Comment by greg-hellings** [comment]
It doesn't need python-krbv. That's only needed if you use Kerberos auth in
Beaker, which we do use, internally.

**Comment by herlo** [comment]
centos-paas-test

**Comment by herlo** [comment]
Should this be against the master branch? I suspect you want this now and not in a future release.

**Comment by robled** [comment]
Yeah, I should have submitted this against the master branch.  I've made a new PR (#191), which does this.  I also changed the name of the dependency to better reflect its purpose.

**Comment by herlo** [comment]
I'd rather you push a new commit here, or rebase and do a push -f to the same branch.

**Comment by herlo** [comment]
NVM. I'll just use 191. But now we know the plan for the future. :)

**Pull request closed without merging**
