### PR TITLE
Linchpin CLI and API units tests and bugfixes

### PR DESCRIPTION
**Pull request by samvarankashyap**
Summary:
Consists of unit tests for Linchpi Cli and API library
few bug fixes to make unit tests run properly.

### CODE REVIEW

**Comment by herlo** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by arilivigni** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Pull request merged**
