### PR TITLE
Openstack performance fix and minor bug fixes for async provisioning

### PR DESCRIPTION
**Pull request by samvarankashyap**
Summary:
1. Wrote a ansible os_server module override to simplify the provision process.
2. Updated playbooks w.r.to new module.
3. Updated openstack inventory filters to parse modified outputs.
4. Minor bug fix in  async provisioning.

### CODE REVIEW

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by herlo** [comment]
Part of the point of linchpin is that it uses the 'standard' ansible modules to provision the system requested. If we are just going to rewrite the module and stick it into our code without submitting to upstream, we cannot track their changes anymore. I think this is going to be very bad, because now we will have a forked codebase and will have to rebase changes in from ansible/os_server module regularly. 

Have you submitted this updated module to upstream as a PR or issue? What will be the process of maintaining changes like this? We are not the maintainers of the ansible modules, though we can be in some cases (like duffy). It seems rather problematic if we keep making changes locally and don't consider how much maintenance will come from adding such a thing.

**Comment by samvarankashyap** [comment]
@herlo : I completely agree with you. I was planning to push os_server module to upstream , as this module will be very useful in case of multiple server provisioning. I will be posting the upstream PR link as soon as I raise a PR.

**Comment by samvarankashyap** [comment]
@herlo : Raised a feature idea, waiting on comments https://github.com/ansible/ansible/issues/20864

**Comment by samvarankashyap** [comment]
@herlo  https://github.com/ansible/ansible/pull/20874 
Feature Pull Request Raised .

**Comment by herlo** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
centos-paas-test

**Comment by samvarankashyap** [comment]
tests passed , successfully.

**Pull request merged**
