### PR TITLE
Rework CLI with a big emphasis on configuration

### PR DESCRIPTION
**Pull request by herlo**
Clean up the linchpin command line interface
------------------------------------------------------------
The linchpin command now provides a simpler interface. The topology and layout functionality has been removed temporarily to ensure a better approach. Below are the current options.

    linchpin
    Usage: linchpin [OPTIONS] COMMAND [ARGS]...

      linchpin: hybrid cloud orchestration

    Options:
      -w, --workspace PATH  Uses the familiar Jenkins $WORKSPACE environment
                            variable
      -v, --verbose         Enable verbose output
      --version             Prints the version and exits
      -h, --help            Show this message and exit.

    Commands:
      init     Initializes a linchpin project.
      up       Provisions nodes from the given target(s) in...
      destroy  Destroys nodes from the given target(s) in...

#########

    linchpin init --help
    Usage: linchpin init [OPTIONS]

      Initializes a linchpin project, which generates an example PinFile, and 
      creates the necessary directory structure for topologies and layouts.

    Options:
      -h, --help  Show this message and exit.

linchpin up (linchpin rise still works)
############################

    linchpin up  --help
    Usage: linchpin up [OPTIONS] TARGET

      Provisions nodes from the given target(s) in the given PinFile.

      TARGET ...
      Provision ONLY the listed target(s).

    Options:
      -p, --pinfile TEXT  Use a name for the PinFile different from the
                          configuration.
      -h, --help          Show this message and exit.

linchpin destroy (linchpin drop still works)
#################################

   linchpin destroy --help
    Usage: linchpin destroy [OPTIONS] TARGET

      Destroys nodes from the given target(s) in the given PinFile.

      TARGET ...
      Destroy ONLY the listed target(s).

    Options:
      -p, --pinfile TEXT  Use a name for the PinFile different from the
                          configuration.
      -h, --help          Show this message and exit.

Additional framework has been put in place for `linchpin down` (currently not implemented).

Standardized vars in roles and linchpin.conf
-------------------------------------------
vars (and extra-vars) are now named consistently throughout the
playbooks and configuration. This is an extension of the linchpin api
functionality which now mostly exists. Here are the new variables with
their previous counterpart(s), with explanations as necessary.

INPUTS
======

The following extra-vars can be passed on the command line with
`ansible-playbook`, using the -e or --extra-vars option.

* topology / topology_file (not changed) - YAML definition
for provisioning and teardown and which providers to use.
* schema / schema_file (schema_v3, schema_v4 are still available) - JSON
description of the format for the topology.
* layout / layout_file (not changed) - YAML definition for providing an
ansible (currently) static inventory file, based upon the provided
topology.
* resources / resources_file (outputs) - File with the resource outputs
in a JSON formatted file. Useful for teardown (destroy,down) actions
depending on the provider.
* inventory / inventory_file (not changed) - If a layout / layout_file
is provided, this will be the location of the resulting ansible inventory.
* workspace (new) - if provided, the above variables will be adjusted
and mapped according to this value. Each path will use the following
variables:
  * topology / topology_file = <workspace>/<topologies_folder>
  * layout / layout_file = <workspace>/<layouts_folder>
  * resources / resources_file = <workspace>/resources_folder>
  * inventory / inventory_file = <workspace>/<inventories_folder>
  * schema is not affected by this pathing
* linchpin_config (new use) - if passed on the command line, should be
an ini-style config file with linchpin default configurations (see
BUILT-INS below for more information)

BUILT-INS
========

These variables SHOULD NOT be changed!!

lp_path (in_code: [common]load_evars_from_ini.yml file_path, value:
<src_dir>/linchpin/) - base path for playbooks and python api
lpconfig (in_code: [common]load_evars_from_ini.yml file_path, value:
<lp_path>/linchpin.conf, unless overridden by linchpin_config (above)

DEFAULTS
========

While the variables here can also be passed as extra-vars, the values
are implied defaults and it is recommended to not pass them. These
values live in the <lp_path>/linchpin.conf by default.

* async (boolean, default: False) - Used to managed asynchronous
provisioning/teardown
* async_timeout (int, default: 1000) - How long the resouce collection
(formerly outputs_writer) process should wait
* output (boolean, default: True, previous: no_output) - Controls
whether resources will be written to the resources_file
* check_mode (boolean, default: no) - This option does nothing at this
time, though it may eventually be used for dry-run functionality based
upon the provider
* schemas_folder (file_path, default: schemas) - relative path to schemas
* playbooks_folder (file_path, default: provision) - relative path to playbooks,
only useful to the linchpin API and CLI
* layouts_folder (file_path, default: layouts) - relative path to layouts
* topologies_folder (file_path, default: topologies) - relative path to topologies
* default_schemas_path (file_path, default: <lp_path>/defaults/<schemas_folder>) -
default path to schemas, absolute path. Can be overridden by passing
schema / schema_file.
* default_playbooks_path (file_path, default:
<lp_path>/defaults/playbooks_folder>) - default path to playbooks
location, only useful to the linchpin API and CLI
* default_layouts_path (file_path, default:
<lp_path>/defaults/<layouts_folder>) - default path to inventory layout
files
* default_topologies_path (file_path, default:
<lp_path>/defaults/<topologies_folder>) - default path to topology
files
* default_resources_path (file_path, default:
<lp_path>/defaults/<resources_folder>, formerly: outputs) - landing
location for resources output data
* default_inventories_path (file_path, default:
<lp_path>/defaults/<inventories_folder>) - landing
location for inventory outputs

DEFAULTS THAT WILL LIKELY CHANGE
`````````````````````````````````````````````````````````
Odds are that these variables will not exist in future version of
linchpin, but are here as temporary stop-gaps to resolve something
problematic until a better solution can be devised.

* schema_v3 (file_path, default:{{ lp_path }}/<default_schemas_path>
/schema_v3.json) - location of v3 of the linchpin JSON schema
* schema_v4 (file_path, default:{{ lp_path }}/<default_schemas_path>
/schema_v4.json) - location of v4 of the linchpin JSON schema

The general approach here is that we use consistent naming conventions for everything. Additionally, this PR has removed all of the variables strewn about the code, consolidating it into the linchpin.conf or passed in on the command line. To accommodate the ansible-playbook method of invocation, adjustments were made (see common/tasks/load_evars_from_ini.yml) to use the linchpin.conf. This also required that a `from_cli` variable be defined in the python API classes. In this way, values were not duplicated.

Please read the commit messages as they are also very descriptive (some of them are included above).

### CODE REVIEW

**Comment by herlo** [comment]
linchpin_rework-img_20170418_153349

**Comment by herlo** [comment]
linchpin_rework-img_20170418_153411
linchpin_rework-img_20170418_153419
linchpin_rework-img_20170418_153426

Design and tracking images posted for reference.

**Comment by samvarankashyap** [comment]
@herlo : 
Installation fails , with few version conflicts in virtualenv. The following requirements.txt will fix the installation issues. 
```
pbr==2.0.0
stevedore<=1.20.0
setuptools>=17.1
oslo.config<3.23.0
oslo.i18n<3.13.0
oslo.serialization<2.17.0
oslo.utils<3.23.0
debtcollector<1.12.0
pyopenssl
requests==2.10.0
ndg-httpsclient
boto>=2.40.0
apache-libcloud>=0.20.1
jsonschema>=2.5.1
shade>=1.9.0
python-openstackclient<3.8.1
click
tabulate
camel
yamlordereddictloader
ansible==2.2.1
```

**Comment by samvarankashyap** [comment]
@herlo : 
```
(pr206) [srallaba@localhost linchtest]$ linchpin --version
Traceback (most recent call last):
  File "/home/srallaba/.virtualenvs/pr206/bin/linchpin", line 11, in <module>
    sys.exit(runcli())
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/decorators.py", line 57, in new_func
    obj = ctx.ensure_object(object_type)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 457, in ensure_object
    self.obj = rv = object_type()
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/linchpin/context.py", line 33, in __init__
    self._load_config()
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/linchpin/context.py", line 81, in _load_config
    ' path: {0}'.format(CONFIG_PATH))
linchpin.api.LinchpinError: Configuration file not found in path: ['/home/srallaba/workspace/venvs/pr206/linchtest/linchpin.conf', '~/.linchpin.conf', '/etc/linchpin.conf', '/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/linchpin/linchpin.conf']
```

**Comment by samvarankashyap** [comment]
@herlo : working requirements.txt
```
pbr!=2.1.0,>=2.0.0
stevedore<=1.20.0
setuptools>=17.1
oslo.config<3.23.0
oslo.i18n<3.13.0
oslo.serialization<2.17.0
oslo.utils<3.23.0
debtcollector<1.12.0
pyopenssl
requests==2.10.0
ndg-httpsclient
boto>=2.40.0
apache-libcloud>=0.20.1
jsonschema>=2.5.1
shade>=1.9.0
python-openstackclient<3.8.1
click
tabulate
camel
yamlordereddictloader
ansible==2.2.1
```

**Comment by samvarankashyap** [comment]
@herlo : linchpin up <target> fails 
fix:: self is missing for find_topology call, it should be self.find_topology in 
linchpin/api/__init__.py +78 
```
(pr206) [srallaba@localhost linchtest]$ linchpin up openstack
Provisioning target: openstack
Traceback (most recent call last):
  File "/home/srallaba/.virtualenvs/pr206/bin/linchpin", line 11, in <module>
    sys.exit(runcli())
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/linchpin/__init__.py", line 141, in up
    lpcli.lp_rise(pf_w_path, targets)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/linchpin/api/__init__.py", line 131, in lp_rise
    self.lp_up(pf, targets)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/linchpin/api/__init__.py", line 151, in lp_up
    self.run_playbook(pinfile, targets, playbook="provision")
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/linchpin/api/__init__.py", line 78, in run_playbook
    self.evars['topology'] = find_topology(pf[target]["topology"],
NameError: global name 'find_topology' is not defined
```

**Comment by samvarankashyap** [comment]
@herlo :  linchpin up single target works
```
(pr206) [srallaba@localhost linchtest]$ linchpin up openstack
Provisioning target: openstack
...
...
TASK [inventory_gen : Parse inventory layout as a ordered dict] ****************
ok: [localhost]

TASK [inventory_gen : Updating inventory_file with the absolute path] **********
ok: [localhost]

TASK [inventory_gen : Generate Generic Inventory] ******************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=28   changed=2    unreachable=0    failed=0  
```

**Comment by samvarankashyap** [comment]
@herlo : linchpin down openstack works
```
(pr206) [srallaba@localhost linchtest]$ linchpin destroy openstack
Provisioning target: openstack

PLAY [schema check and Pre Provisioning Activities on topology_file] ***********

TASK [common : use lnchpin_config if provided] *********************************
skipping: [localhost]
...
...
TASK [inventory_gen : Generate Generic Inventory] ******************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=22   changed=1    unreachable=0    failed=0   
```

**Comment by samvarankashyap** [comment]
@herlo :  linchpin rise aws works 
```
(pr206) [srallaba@localhost linchtest]$ linchpin rise aws
Provisioning target: aws

PLAY [schema check and Pre Provisioning Activities on topology_file] ***********

TASK [common : use lnchpin_config if provided] *********************************
skipping: [localhost]

TASK [common : set lp_path] ****************************************************
skipping: [localhost]
...
...
TASK [inventory_gen : Updating inventory_file with the absolute path] **********
ok: [localhost]

TASK [inventory_gen : Generate Generic Inventory] ******************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=28   changed=3    unreachable=0    failed=0   

```

**Comment by samvarankashyap** [comment]
@herlo  linchpin drop/destroy aws  doesn't work !!
```
(pr206) [srallaba@localhost linchtest]$ linchpin drop aws
Provisioning target: aws

PLAY [schema check and Pre Provisioning Activities on topology_file] ***********

TASK [common : use lnchpin_config if provided] *********************************
skipping: [localhost]
...
...
TASK [inventory_gen : Generate Generic Inventory] ******************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=15   changed=0    unreachable=0    failed=0   
```

**Comment by samvarankashyap** [comment]
@herlo : linchpin destroy aws bugfix : 

https://github.com/herlo/linch-pin/blob/cli_config_rework/linchpin/provision/roles/aws/tasks/main.yml#L25
line 25
should be as follows : 
```
- "{{ resources_file| default( default_resources_path+'/'+outputs.topology_name+'.output') }}"
```

**Comment by samvarankashyap** [comment]
linchpin rise gcloud works 
(pr206) [srallaba@localhost linchtest]$ linchpin rise gcloud
...
TASK [inventory_gen : Updating inventory_file with the absolute path] **********
ok: [localhost]
TASK [inventory_gen : Generate Generic Inventory] ******************************
changed: [localhost]
PLAY RECAP *********************************************************************
localhost                  : ok=28   changed=3    unreachable=0    failed=0

**Comment by samvarankashyap** [comment]
@herlo linchpin drop gcloud works!
(pr206) [srallaba@localhost linchtest]$ linchpin destroy gcloud
...
TASK [inventory_gen : Generate Generic Inventory] ******************************
skipping: [localhost]
PLAY RECAP *********************************************************************
localhost                  : ok=22   changed=1    unreachable=0    failed=0

**Comment by samvarankashyap** [comment]
@herlo : 
linchpin rise/drop with multiple targets works !

**Comment by samvarankashyap** [comment]
@herlo : 
Note: 
The following operations are being commented out in the current PR . 
linchpin invgen  # generates inventories based on outputs, layouts
linchpin validate # validates topology files
linchpin topology get # fetches topologies from both local , and github repo 
linchpin layout get  # fetches layouts from both local and github repo .
These above functionalities should be rewritten according to the changes proposed in #206 

Ref: [#210](https://github.com/CentOS-PaaS-SIG/linch-pin/issues/210)

**Comment by herlo** [comment]
A simple test for the -c option would be to copy the linchpin.conf to /tmp, say. Then, update 'enable = True' under the [logger] section. When run, a file called linchpin.log will be created with some log messages in it in the execution directory.

**Comment by samvarankashyap** [comment]
@herlo :  regression due to new commit 
fix:: self is missing for find_topology call, it should be self.find_topology in
linchpin/api/init.py +65
wonder why it occurred again , ??? 
(pr206) [srallaba@localhost linchtest]$ linchpin rise aws 
provision target: aws
Traceback (most recent call last):
  File "/home/srallaba/.virtualenvs/pr206/bin/linchpin", line 11, in <module>
    sys.exit(runcli())
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/linchpin/__init__.py", line 148, in up
    lpcli.lp_rise(pf_w_path, targets)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/linchpin/api/__init__.py", line 118, in lp_rise
    self.lp_up(pf, targets)
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/linchpin/api/__init__.py", line 138, in lp_up
    self.run_playbook(pinfile, targets, playbook="provision")
  File "/home/srallaba/.virtualenvs/pr206/lib/python2.7/site-packages/linchpin/api/__init__.py", line 65, in run_playbook
    self.ctx.evars['topology'] = find_topology(pf[target]["topology"],
NameError: global name 'find_topology' is not defined

**Comment by herlo** [comment]
Fixes #207 - knocked it out while here, seemed like a good idea
Fixes #202 - linchpin_config.yml is no longer
Fixes #119 - pass -w or --workspace
Fixes #199 - linchpin config init no longer exists

**Pull request merged**
