### PR TITLE
*HOTFIX* Fixes #171 - incorrect schema version

### LINKED ISSUE #171: linchpin provision beaker machine with example topology fails with error missing required property
Linchpin fails with missing required property 'res_defs' trying to provision a beaker machine using example beaker topology.

PLAY [including the configuration files] ***************************************

TASK [Include linchpin_config] *************************************************
ok: [localhost] => (item=/usr/linchpin_config.yml)

PLAY [schema check and Pre Provisioning Activities  on topology_file] **********

TASK [common : DEBUG: topology and schema] *************************************
ok: [localhost] => {
    "msg": "topology: /root/sjm-run-test/topologies/beaker.yml schema: /root/linchpin/lib/python2.7/site-packages/ex_schemas/schema_v2.json"
}

TASK [common : schema check for given topology file] ***************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": {"content": {"error": "u'res_defs' is a required property", "status": false}, "path": "/root/sjm-run-test/topologies/beaker.yml"}}
	to retry, use: --limit @/root/linchpin/lib/python2.7/site-packages/provision/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   

---
topology_name: beaker
resource_groups:
  - resource_group_name: test1
    res_group_type: beaker
    job_group: ci-ops-central
    recipesets:
      - distro: RHEL-6.5
        arch: x86_64
        arches:
          - X86_64
          - X86_64
        keyvalue:
          - MEMORY>1000
          - DISKSPACE>20000
        hostrequire:
          - arch=X86_64
        count: 1

### PR DESCRIPTION
**Pull request by herlo**
`linchpin config --reset` now generates correct schema

### CODE REVIEW

**Comment by herlo** [comment]
centos-paas-test

**Comment by robled** [comment]
Will this fix only affect the `linchpin config --reset` command or will it also affect the config files that are generated as part of the pip installation?  Based on my testing in #171 we've got multiple config files that are generated, and one of them refers to schema_v2 and the other to schema_v3.

**Comment by herlo** [comment]
This should address anything related to generating the config after
installation.

The installation generates the linchpin_config.yml correctly already. It's
just that the application cannot find it in the search path in certain
scenarios. We are addressing this in the 1.0.0 release as previously
discussed.

@herlo

**Comment by robled** [comment]
Excellent, thank you!

**Pull request merged**
